# Databricks notebook source
# MAGIC %sql
# MAGIC CREATE SCHEMA IF NOT EXISTS llm;
# MAGIC
# MAGIC CREATE TABLE IF NOT EXISTS llm.call_logs (call_id string, caller_id string, receiver_id string, call_start_time timestamp, call_end_time timestamp, transcription string, agent_notes string, fraud_label BOOLEAN) tblproperties (delta.enableChangeDataFeed = true);
# MAGIC
# MAGIC CREATE TABLE IF NOT EXISTS llm.feedback (call_id string, note string, fraud BOOLEAN, uid string, update_time timestamp) tblproperties (delta.enableChangeDataFeed = true);
# MAGIC
# MAGIC CREATE TABLE IF NOT EXISTS llm.fraud_summary (call_id string, fraud_probability float, fraud_pattern string, explanation string, summary_txt string, update_time timestamp) tblproperties (delta.enableChangeDataFeed = true);
# MAGIC
# MAGIC CREATE TABLE IF NOT EXISTS llm.sentiment_analysis (call_id string, customer_sentiment string, customer_explanation string, agent_sentiment string, agent_explanation string) tblproperties (delta.enableChangeDataFeed = true);

# COMMAND ----------

# MAGIC %sql
# MAGIC CREATE TABLE llm.call_logs as select call_id, transcription from llm.synthetic_call_data where label = 1

# COMMAND ----------

# MAGIC %sql
# MAGIC CREATE TABLE IF NOT EXISTS llm.fraud_summary_chunks (id BIGINT GENERATED BY DEFAULT AS IDENTITY, fraud_probability float, fraud_pattern string, explanation string, summary_txt string) tblproperties (delta.enableChangeDataFeed = true);
# MAGIC
# MAGIC INSERT INTO llm.fraud_summary_chunks (fraud_probability, fraud_pattern, explanation, summary_txt ) SELECT  fraud_probability, fraud_pattern, explanation, summary FROM llm.fraud_analysis_summary;

# COMMAND ----------

# MAGIC %sql
# MAGIC SELECT count(*)  FROM llm.fraud_analysis_summary;
